### PR TITLE
Replace deprecated interfaces with their replacements for Bitbucket 6

### PR DESCRIPTION
**Pull request by matmannion**
This allows the add-on to support Bitbucket 6.

### CODE REVIEW

**Comment by petermcd** [comment]
The changes made here, does this allow the plugin to fully work with v6 of Bitbucket or is it a partial fix?

**Comment by matmannion** [comment]
@petermcd it fully works with v6 with these changes.

**Comment by adrianluisgonzalez** [comment]
Apologies for the radio silence.  I will try to get this merged and have a new build on the market place this week.

**Comment by petermcd** [comment]
Just upgraded using the GUI and can see a flurry of commits to my mirrored github repos.

fyi you should be able to close issue #69

**Pull request merged**
